import { Link } from 'react-router-dom';
import { Card } from '@/components/ui/Card';
import { useCosting } from '@/context/CostingContext';
import { CostBreakdown } from '@/pages/Costing/CustomCosting';
import type { JobCard } from '@/types';
export function JobCosting({ card }: { card: JobCard }) {
  const { estimates } = useCosting(); const estimate = estimates.find(e => e.id === card.estimateId);
  return <Card className="space-y-4"><h2 className="font-semibold text-navy">Estimated Cost vs Actual Production Cost</h2><Link to={`/costing?orderId=${card.salesOrderId}&itemId=${card.salesOrderItemId ?? ''}`} className="text-sm underline">Open Linked Costing / Estimate</Link>{estimate ? <><p className="text-sm">{estimate.number} · Estimate Revision {estimate.revision} · Model Revision {card.modelRevision} · Costing: {estimate.status} · Customer Acceptance: {estimate.customerAcceptance}</p>{estimate.reviewReason && <p className="text-amber-700">{estimate.reviewReason}</p>}<CostBreakdown estimate={estimate} /><h3 className="font-semibold">Estimated Process Costs</h3>{estimate.input.processes.map((p, i) => <p key={p.id} className="text-sm">{p.name} · {p.basis} · {p.rate} × {p.basis === 'fixed' ? 1 : p.quantity} · {estimate.input.currency} {estimate.totals.processCosts[i].toFixed(2)} · {p.remarks}</p>)}<p className="text-sm">Planned Waste Allowance: {estimate.input.wastePercent}% · Basis: {estimate.input.wasteBasis}</p></> : <p className="text-sm text-gray-500">No linked costing revision. Legacy job data does not contain an approved estimate.</p>}<dl className="grid gap-3 sm:grid-cols-3"><div><dt>Estimated Cost</dt><dd>{estimate?.approvedAt ? `${estimate.input.currency} ${estimate.totals.costOfProduction.toFixed(2)}` : 'Approved costing unavailable'}</dd></div><div><dt>Actual Cost</dt><dd>Unavailable — consumption and actual process prices are not recorded</dd></div><div><dt>Variance</dt><dd>Unavailable until actual costs are recorded</dd></div></dl></Card>;
}
