import { FINISHED_GOODS, finishedGoodLabel } from '@/lib/finishedGoodsData';
import { ENTRY_INPUT } from '@/components/ui/SearchSelect';
import { JobRoutingEditor } from './JobRoutingEditor';
import { JobCosting } from './JobCosting';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { useAuth } from '@/context/AuthContext';
import { useJobCards } from '@/context/JobCardsContext';
import { useInventory } from '@/context/InventoryContext';
import { RAW_MATERIALS, rawMaterialBalance } from '@/lib/rawMaterialData';
import { PRODUCTION_STATUS_LABELS, currentLocation, fmtQuantity, isDelayed, orderedStages, productionStages, productionTotals } from '@/lib/jobCards';
import { JOB_BUTTON, JOB_PRIMARY, JobFields, JobProgress, JobStatus, jobDate } from './JobCardUI';
import { JobEditForm, MaterialIssueForm, StageUpdateForm, StockTransferForm } from './JobCardForms';

const tabs = ['Overview', 'Materials', 'Costing', 'Production Routing', 'Production Tracking', 'Waste', 'Activity History'] as const;
type Tab = typeof tabs[number];
export function JobCardDetail() {
  const { id = '' } = useParams();
  const { user } = useAuth();
  const { cards, loadDetail, approve, edit, issue, updateStage, transfer, postPreparedReceipts, toggleStage, saveSequence } = useJobCards();
  const { rawMovements } = useInventory();
  const [detailLoading, setDetailLoading] = useState(true);
  const [tab, setTab] = useState<Tab>('Overview');
  const [form, setForm] = useState<'edit' | 'issue' | 'transfer' | null>(null);
  const [stageId, setStageId] = useState<string | null>(null);
  const [stockProduct, setStockProduct] = useState('');
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; setDetailLoading(true); setTab('Overview'); setForm(null); setStageId(null); setNotice(''); setError(''); void loadDetail(id).finally(() => { if (active) setDetailLoading(false); }); return () => { active = false; }; }, [id, loadDetail]);
  const card = cards.find(c => c.id === id);
  if (detailLoading) return <p role="status" className="text-sm text-gray-500">Loading job card…</p>;
  if (!card) return <Card><h1 className="text-xl font-semibold text-navy">Job card not found</h1><p className="mt-2 text-sm text-gray-500">No Job Card record exists for this reference.</p><Link to="/job-cards" className={`${JOB_BUTTON} mt-4`}>Back to Job Cards</Link></Card>;
  const location = currentLocation(card), totals = productionTotals(card);
  const stages = orderedStages(card), required = productionStages(card);
  const materials = card.requiredMaterials ?? [];
  const canApprove = ['production_manager', 'admin'].includes(user?.role ?? '') && ['Draft', 'PendingApproval'].includes(card.status);
  const canConfigure = ['production_manager', 'admin'].includes(user?.role ?? '') && !card.approval && ['Draft', 'PendingApproval'].includes(card.status);
  const canIssue = ['store_keeper', 'admin'].includes(user?.role ?? '') && ['Approved', 'StoreIssuePending', 'MaterialIssued', 'Issued'].includes(card.status) && materials.some(m => m.issuedQuantity < m.requiredQuantity);
  const canProduce = ['production_operator', 'production_manager', 'admin'].includes(user?.role ?? '') && ['MaterialIssued', 'Issued', 'InProduction', 'OnHold'].includes(card.status);
  const canTransfer = ['store_keeper', 'admin'].includes(user?.role ?? '') && card.status === 'ReadyForStock' && (totals.produced ?? 0) > (card.acceptedQuantity ?? 0) + (card.rejectedQuantity ?? 0);
  const available = Object.fromEntries(materials.map(m => { const material = RAW_MATERIALS.find(raw => raw.id === m.materialId && raw.unit === m.unit); return [m.id, material ? rawMaterialBalance(material, rawMovements).currentStock : null]; }));
  const selectedStage = stages.find(s => s.id === stageId);
  const run = (action: () => void, message: string) => { try { action(); setNotice(message); setError(''); } catch (error) { setError(error instanceof Error ? error.message : 'Unable to update job card'); } };
  const save = async () => { setSaving(true); try { const persisted = await saveSequence(card.id); setNotice(persisted ? 'Stage API accepted the request. Manufacturing tracking remains frontend-only.' : 'Stage requirements saved in frontend state only; API unavailable.'); setError(''); } catch (error) { setError(error instanceof Error ? error.message : 'Unable to save stage requirements'); } finally { setSaving(false); } };
  const overviewFields: [string, string][] = [['Job Card No.', card.jobCardNumber], ['Sales Order No.', card.salesOrderNumber ?? 'Not recorded'], ['Customer', card.customerName ?? 'Not recorded'], ['Model', card.modelName], ['Model Revision', String(card.modelRevision ?? 'Not recorded')], ['Costing Revision', String(card.estimateRevision ?? 'Not recorded')], ['Product', card.product ?? 'Not recorded'], ['Specifications', card.specifications ?? 'Not recorded'], ['Order Quantity', fmtQuantity(card.qty, card.unit)], ['Required Date', jobDate(card.requiredDate)], ['Created Date', jobDate(card.createdDate)], ['Production Requirements', card.productionRequirements ?? 'Not configured'], ['Current Department', location.department], ['Current Stage', location.stage]];
  return <div className="space-y-6">
    <Link to="/job-cards" className="inline-flex items-center gap-2 text-sm text-navy hover:underline"><ArrowLeft size={16} />Back to Job Cards</Link>
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-navy">{card.jobCardNumber}</h1><p className="mt-1 text-sm text-gray-500">Sales Order: <Link to={`/sales-orders/${card.salesOrderId}`} className="font-medium text-navy underline" title="Open the existing Sales Orders list">{card.salesOrderNumber ?? card.salesOrderId}</Link> · {card.customerName ?? 'Customer not recorded'}</p></div><div className="flex flex-wrap items-center gap-2"><JobStatus card={card} />{isDelayed(card) && <StatusBadge status="Delayed" />}{canApprove && <><button className={JOB_BUTTON} onClick={() => setForm('edit')}>Edit</button><button className={JOB_PRIMARY} onClick={() => run(() => approve(card.id), 'Approved and forwarded to Store Issue Pending.')}>Approve</button></>}{canIssue && <button className={JOB_PRIMARY} onClick={() => setForm('issue')}>Issue Materials</button>}{canTransfer && <button className={JOB_PRIMARY} onClick={() => setForm('transfer')}>Transfer to Finished Goods</button>}</div></header>
    <p className="text-xs text-gray-500">Frontend manufacturing tracking. Changes survive navigation and reset on refresh. Material issue and recycling remain tracking-only; accepted Finished Goods receipts post to shared frontend inventory for linked products. No data is persistent.</p>
    {notice && <p role="status" className="rounded-card bg-green/10 px-4 py-3 text-sm text-green">{notice}</p>}{error && <p role="alert" className="rounded-card bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    <Card className="space-y-5"><JobFields fields={overviewFields.filter(([label]) => !['Specifications', 'Production Requirements', 'Job Card No.', 'Sales Order No.'].includes(label))} /><JobProgress card={card} /></Card>
    {(card.status === 'ReadyForStock' || card.status === 'Completed') && <Card className="space-y-4"><h2 className="font-semibold text-navy">{card.status === 'Completed' ? 'Stock Keeping Confirmed' : 'Ready for Stock'}</h2><JobFields fields={[["Order Quantity", fmtQuantity(card.qty, card.unit)], ['Total Produced (final production stage)', fmtQuantity(totals.produced, totals.unit)], ['Total Waste (by unit)', totals.waste], ['Accepted Finished Quantity', fmtQuantity(card.acceptedQuantity, card.stockTransfer?.unit ?? totals.unit)], ['Production / Batch Date', jobDate(card.stockTransfer?.batchDate)], ['Confirmed By', card.stockTransfer?.confirmedBy ?? 'Not confirmed']]} /></Card>}
    <div role="tablist" aria-label="Job card details" className="flex flex-wrap gap-x-6 gap-y-3 border-b border-gray-200">{tabs.map((name, index) => <button key={name} role="tab" id={`job-tab-${index}`} aria-selected={tab === name} aria-controls={`job-panel-${index}`} onClick={() => setTab(name)} className={`-mb-px border-b-2 pb-3 text-sm font-medium ${tab === name ? 'border-navy text-navy' : 'border-transparent text-gray-500 hover:text-navy'}`}>{name}</button>)}</div>
    <section role="tabpanel" id={`job-panel-${tabs.indexOf(tab)}`} aria-labelledby={`job-tab-${tabs.indexOf(tab)}`}>
      {tab === 'Overview' && <Card className="space-y-6"><JobFields fields={overviewFields} /><div><h2 className="mb-3 font-semibold text-navy">Overall Status</h2><JobStatus card={card} /></div><div><h2 className="mb-2 font-semibold text-navy">Approval</h2>{card.approval ? <JobFields fields={[["Approval Status", 'Approved'], ['Approved By', card.approval.approvedBy], ['Approved Date/Time', jobDate(card.approval.approvedAt)]]} /> : <p className="text-sm text-gray-500">{['PendingApproval', 'Draft'].includes(card.status) ? 'Pending Production Manager approval.' : 'Approval details not recorded.'}</p>}</div><div><h2 className="mb-2 font-semibold text-navy">Manufacturing Workflow</h2><p className="text-sm leading-7 text-gray-600">Sales Order → Job Card → Production Manager Approval → Store Issue → Production → Finished Goods → Stock Keeping</p></div></Card>}
      {tab === 'Materials' && <Card className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold text-navy">Required Materials</h2>{canIssue && <button className={JOB_PRIMARY} onClick={() => setForm('issue')}>Issue Materials</button>}</div><p className="text-xs text-gray-500">Requirements come from Job Card data. Automatic model/points calculations await backend integration.</p><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr>{['Material', 'Required Quantity', 'Unit', 'Issued Quantity', 'Balance Quantity', 'Issue Status'].map(label => <th key={label} scope="col" className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{materials.map(m => <tr key={m.id}><td className="px-4 py-3 font-medium text-navy">{m.name}</td><td className="px-4 py-3">{fmtQuantity(m.requiredQuantity)}</td><td className="px-4 py-3">{m.unit}</td><td className="px-4 py-3">{fmtQuantity(m.issuedQuantity)}</td><td className="px-4 py-3">{fmtQuantity(Math.max(0, m.requiredQuantity - m.issuedQuantity))}</td><td className="px-4 py-3"><StatusBadge status={m.issuedQuantity >= m.requiredQuantity ? 'Issued' : m.issuedQuantity > 0 ? 'Partial' : 'Pending'} /></td></tr>)}{!materials.length && <tr><td colSpan={6} className="p-6 text-center text-gray-500">Required materials are not configured for this Job Card.</td></tr>}</tbody></table></div></Card>}
      {tab === 'Costing' && <JobCosting card={card} />}
      {tab === 'Production Routing' && <JobRoutingEditor key={`${card.id}-${card.routingRevision}-${card.estimateId}-${!!card.approval}`} card={card} />}
      {tab === 'Production Tracking' && <Card className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold text-navy">Production Stages</h2>{canConfigure && <button disabled={saving} className={JOB_BUTTON} onClick={() => void save()}>{saving ? 'Saving…' : 'Save stage sequence'}</button>}</div><p className="text-xs text-gray-500">Stages follow the Job Card's model-specific array. Expand a stage for quantities, units and handover details. Only pending stages can be added or removed; recorded production is preserved.</p><div className="space-y-3">{stages.map(stage => {
        const priorComplete = required.filter(s => s.sequence < stage.sequence).every(s => s.status === 'Completed');
        return <details key={stage.id} className={`rounded-card border p-4 ${!stage.required ? 'border-dashed border-gray-200 bg-gray-50' : stage.status === 'OnHold' ? 'border-amber-300 bg-amber-50' : location.stage === stage.name ? 'border-navy/30 bg-navy/5' : 'border-gray-200'}`}><summary className="cursor-pointer text-sm font-medium text-navy">{stage.sequence}. {stage.name} · {stage.department} <span className="ml-2"><StatusBadge status={stage.required ? PRODUCTION_STATUS_LABELS[stage.status] : 'Not Required'} /></span></summary><div className="mt-4 space-y-4"><JobFields fields={[["Stage Name", stage.name], ['Department', stage.department], ['Sequence', String(stage.sequence)], ['Input Quantity', fmtQuantity(stage.inputQuantity, stage.inputUnit)], ['Output Quantity', fmtQuantity(stage.outputQuantity, stage.outputUnit)], ['Waste Quantity', fmtQuantity(stage.wasteQuantity, stage.wasteUnit)], ['Started Date/Time', jobDate(stage.startedAt)], ['Completed Date/Time', jobDate(stage.completedAt)], ['Operator / Responsible Person', stage.operator || 'Not assigned'], ['Machine', stage.machine || 'Not configured'], ['Planned Input', fmtQuantity(stage.expectedInput, stage.inputUnit)], ['Planned Output / Yield', fmtQuantity(stage.expectedOutput, stage.outputUnit)], ['Instructions', stage.instructions || '—'], ['Remarks', stage.remarks || '—']]} />{stage.handover && <p className="text-sm text-gray-600">Previous stage sent {fmtQuantity(stage.handover.quantity, stage.handover.unit)}.{stage.inputUnit !== stage.handover.unit ? ' Different input units require an explicit received quantity.' : ''}</p>}<div className="flex flex-wrap gap-2">{canProduce && stage.required && stage.kind === 'production' && stage.status !== 'Completed' && priorComplete && <button className={JOB_PRIMARY} onClick={() => setStageId(stage.id)}>Update {stage.name}</button>}{canConfigure && !card.estimateId && stage.status === 'Pending' && <button className={JOB_BUTTON} onClick={() => run(() => toggleStage(card.id, stage.id), 'Stage requirement updated in frontend state.')}>{stage.required ? 'Remove stage' : 'Add stage'}</button>}</div>{stage.status === 'Completed' && <p className="text-xs text-gray-500">Completed stage record — view only.</p>}{stage.kind === 'stock' && stage.status !== 'Completed' && <p className="text-xs text-gray-500">Stock Keeping is confirmed using Transfer to Finished Goods after required production is complete.</p>}</div></details>;
      })}{!stages.length && <p className="text-sm text-gray-500">Production stages are not configured.</p>}</div></Card>}
      {tab === 'Waste' && <Card className="space-y-4"><h2 className="font-semibold text-navy">Job Card Waste</h2><p className="text-xs text-gray-500">Derived from this Job Card's production-stage records. Recycling quantities are frontend tracking only.</p><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr>{['Date', 'Item', 'Model', 'Job Card', 'Department / Process', 'Production Quantity', 'Waste Quantity', 'Waste Type / Category', 'Reason', 'Quantity Sent to Recycling', 'Remaining Waste', 'Remarks'].map(label => <th key={label} scope="col" className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{stages.filter(s => s.required && (s.wasteQuantity ?? 0) > 0).map(s => <tr key={s.id}>{[jobDate(s.completedAt ?? s.startedAt), card.product ?? card.modelName, card.modelName, card.jobCardNumber, `${s.department} / ${s.name}`, fmtQuantity(s.outputQuantity, s.outputUnit), fmtQuantity(s.wasteQuantity, s.wasteUnit), s.wasteType || 'Not recorded', s.wasteReason || 'Not recorded', fmtQuantity(s.sentToRecycling ?? 0, s.wasteUnit), fmtQuantity(Math.max(0, s.wasteQuantity! - (s.sentToRecycling ?? 0)), s.wasteUnit), s.remarks || '—'].map((value, index) => <td key={index} className="px-4 py-3">{value}</td>)}</tr>)}{!stages.some(s => s.required && (s.wasteQuantity ?? 0) > 0) && <tr><td colSpan={12} className="p-6 text-center text-gray-500">No positive waste quantities recorded for this Job Card.</td></tr>}</tbody></table></div></Card>}
      {tab === 'Activity History' && <Card className="space-y-4"><h2 className="font-semibold text-navy">Activity History</h2><p className="text-xs text-gray-500">Frontend timeline; new entries reset on refresh.</p><ol className="space-y-4">{[...(card.activityHistory ?? [])].sort((a, b) => a.timestamp.localeCompare(b.timestamp)).map(activity => <li key={activity.id} className="border-l-2 border-green/30 pl-4"><p className="text-xs text-gray-500">{jobDate(activity.timestamp)} · {activity.user} · {activity.department}</p><h3 className="mt-1 text-sm font-medium text-navy">{activity.action}</h3><p className="mt-1 text-sm text-gray-600">{activity.description}</p></li>)}</ol>{!card.activityHistory?.length && <p className="text-sm text-gray-500">No activity history provided for this Job Card.</p>}</Card>}
    </section>
    {form === 'edit' && <JobEditForm card={card} onClose={() => setForm(null)} onSave={change => { edit(card.id, change); setNotice('Job Card updated in frontend state.'); }} />}
    {form === 'issue' && <MaterialIssueForm card={card} available={available} onClose={() => setForm(null)} onSave={quantities => { issue(card.id, quantities, available); setNotice('Material issue recorded in frontend state. Raw Material stock is unchanged.'); }} />}
    {selectedStage && <StageUpdateForm lockUnits={!!card.estimateId && !!card.routingApproved} stage={selectedStage} operator={user?.name ?? ''} onClose={() => setStageId(null)} onSave={update => { updateStage(card.id, selectedStage.id, update); setNotice('Production stage updated; handover and activity recorded in frontend state.'); }} />}
    {card.stockReceiptPending && <Card className="space-y-3"><h2 className="font-semibold text-navy">QC receipt prepared — inventory mapping required</h2><p className="text-sm text-amber-700">Finished Goods stock has not changed. Map the exact variant in the output unit. If none exists, authoritative product/unit setup is required; no piece/carton conversion is inferred.</p>{['admin', 'store_keeper'].includes(user?.role ?? '') && <><label>Finished Product<select value={stockProduct} onChange={e => setStockProduct(e.target.value)} className={ENTRY_INPUT}><option value="">Select exact stock variant</option>{FINISHED_GOODS.filter(p => p.unit === card.stockTransfer?.unit).map(p => <option key={p.id} value={p.id}>{finishedGoodLabel(p)}</option>)}</select></label><button className={JOB_PRIMARY} onClick={() => run(() => postPreparedReceipts(card.id, stockProduct), 'QC-prepared receipts posted to shared Finished Goods inventory.')}>Post Prepared Stock IN</button></>}</Card>}
    {!!card.stockTransfers?.length && <Card className="space-y-3"><h2 className="font-semibold text-navy">Finished Goods receipt batches</h2>{card.stockTransfers.map(receipt => <p key={receipt.id} className="text-sm">{receipt.date} · {receipt.batch} · Accepted {receipt.quantity} {card.stockTransfer?.unit} · Rejected {receipt.rejectedQuantity} · <Link to="/stock" className="underline">Stock transaction {receipt.id}</Link></p>)}</Card>}
    {form === 'transfer'  && <StockTransferForm card={card} onClose={() => setForm(null)} onSave={(quantity, date, receipt) => { transfer(card.id, quantity, date, receipt); setNotice(card.finishedProductId ? 'QC-confirmed receipt posted to shared Finished Goods Stock IN.' : 'QC-confirmed receipt prepared. Map an exact finished product to post stock.'); }} />}
  </div>;
}
