import type { JobProductionStage } from '@/types';
import { ENTRY_INPUT } from '@/components/ui/SearchSelect';
export const newRoutingStage = (): JobProductionStage => ({ id: crypto.randomUUID(), name: '', department: '', sequence: 1, required: true, kind: 'production', status: 'Pending', inputQuantity: null, outputQuantity: null, wasteQuantity: null, inputUnit: '', outputUnit: '', wasteUnit: '', operator: '', remarks: '' });
export function RoutingFields({ stages, onChange, readOnly = false }: { stages: JobProductionStage[]; onChange: (stages: JobProductionStage[]) => void; readOnly?: boolean }) {
  const publish = (next: JobProductionStage[]) => onChange(next.map((s, i) => ({ ...s, sequence: i + 1 })));
  const edit = (id: string, change: Partial<JobProductionStage>) => publish(stages.map(s => s.id === id ? { ...s, ...change } : s));
  const move = (i: number, direction: number) => { const next = [...stages]; [next[i], next[i + direction]] = [next[i + direction], next[i]]; publish(next); };
  return <div className="space-y-3">{stages.map((s, i) => <fieldset key={s.id} disabled={readOnly} className="space-y-3 rounded-card border border-gray-200 p-4"><legend className="px-2 text-sm font-medium text-navy">Stage {i + 1}</legend><div className="grid gap-3 sm:grid-cols-3">{(['name', 'department', 'machine', 'inputUnit', 'outputUnit', 'wasteUnit', 'instructions'] as const).map(key => <label key={key} className="text-sm text-gray-600">{{ name: 'Process Name', department: 'Department', machine: 'Machine (optional)', inputUnit: 'Expected Input Unit', outputUnit: 'Expected Output Unit', wasteUnit: 'Waste Unit', instructions: 'Production Instructions' }[key]}<input value={s[key] ?? ''} onChange={e => edit(s.id, { [key]: e.target.value })} className={ENTRY_INPUT} /></label>)}{(['expectedInput', 'expectedOutput', 'plannedWastePercent'] as const).map(key => <label key={key} className="text-sm text-gray-600">{{ expectedInput: 'Planned Input Quantity', expectedOutput: 'Planned Output Quantity / Yield', plannedWastePercent: 'Planned Waste %' }[key]}<input type="number" min="0" step="any" value={s[key] ?? ''} onChange={e => edit(s.id, { [key]: e.target.value === '' ? undefined : e.target.valueAsNumber })} className={ENTRY_INPUT} /></label>)}</div><label className="mr-3 text-sm"><input type="checkbox" checked={s.required} onChange={e => edit(s.id, { required: e.target.checked })} /> Mandatory stage</label><button type="button" disabled={i === 0} onClick={() => move(i, -1)} className="mr-3 text-sm text-navy disabled:opacity-40">Move up</button><button type="button" disabled={i === stages.length - 1} onClick={() => move(i, 1)} className="mr-3 text-sm text-navy disabled:opacity-40">Move down</button><button type="button" onClick={() => publish(stages.filter(row => row.id !== s.id))} className="text-sm text-red-700">Remove</button></fieldset>)}{!readOnly && <button type="button" onClick={() => publish([...stages, newRoutingStage()])} className="rounded-card border px-3 py-2 text-sm text-navy">Add production stage</button>}{!stages.length && <p className="text-sm text-gray-500">No configured route. Add model-specific processes for PM review.</p>}</div>;
}
