import { useEffect, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useSalesOrders } from '@/context/SalesOrdersContext';
import { useInventory } from '@/context/InventoryContext';
import { useJobCards } from '@/context/JobCardsContext';
import { useAuth } from '@/context/AuthContext';
import { FINISHED_BY_ID } from '@/lib/finishedGoodsData';
import { reserved, physical } from '@/lib/fulfillment';
import { useModels } from '@/context/ModelsContext';
import { useCosting } from '@/context/CostingContext';
import { RAW_MATERIALS } from '@/lib/rawMaterialData';
import { today } from '@/lib/salesOrders';
import { Card } from '@/components/ui/Card';
import { ENTRY_INPUT } from '@/components/ui/SearchSelect';
import { InvoiceForm, InvoiceView } from './SalesInvoice';
import { useInvoices } from '@/context/InvoicesContext';
const button = 'rounded-card border border-gray-200 px-3 py-2 text-sm text-navy';
export function SalesOrderDetail() {
  const { versions } = useModels(); const { estimates } = useCosting();
  const { id } = useParams(); const { orders } = useSalesOrders(); const order = orders.find(o => o.id === id);
  const { ledger, allocateStock, dispatch, reverse } = useInventory(); const { cards, load, createLinked } = useJobCards(); const { user } = useAuth(); const { invoices } = useInvoices();
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [invoiceOpen, setInvoiceOpen] = useState(false);
  useEffect(() => { void load(); }, [load]);
  const run = (action: () => void) => { try { action(); setError(''); setNotice('Recorded in frontend session state.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save.'); } };
  if (!order) return <Card>Sales Order not found. <Link to="/sales-orders">Return to orders</Link></Card>;
  const canFulfill = !!user && ['admin', 'store_keeper', 'receptionist'].includes(user.role);
  return <div className="space-y-5"><Link to="/sales-orders" className="text-navy underline">Sales Orders</Link><h1 className="text-2xl font-semibold text-navy">{order.orderNumber} · {order.customerName}</h1><p className="text-sm text-gray-500">{order.date} · {order.customerType} · Marketing: {order.marketingPersonName} · Customer PO: {order.requisitionOrder || 'Not recorded'}</p><p className="rounded-card bg-sky-50 p-3 text-sm text-sky-800">Frontend simulation. All receipts, reservations, dispatches and invoices reset on refresh. Quantities retain their own units.</p>{error && <p role="alert" className="text-red-700">{error}</p>}{notice && <p role="status">{notice}</p>}
    {order.items?.map(item => {
      const allocations = ledger.allocations.filter(a => a.orderId === order.id && a.itemId === item.id);
      const jobs = cards.filter(c => c.salesOrderId === order.id && c.salesOrderItemId === item.id);
      const sent = ledger.dispatches.filter(d => d.orderId === order.id && d.itemId === item.id && d.status === 'Confirmed').reduce((sum, d) => sum + d.quantity, 0);
      const received = ledger.movements.filter(m => m.salesOrderId === order.id && m.salesOrderItemId === item.id && m.jobCardId && m.type === 'IN').reduce((sum, m) => sum + m.quantity, 0);
      const allocated = allocations.filter(a => !a.released).reduce((sum, a) => sum + a.quantity - a.dispatched, 0);
      const status = sent === item.quantity ? 'Dispatched' : sent > 0 ? 'Partially Dispatched' : allocated > 0 ? 'Reserved' : received > 0 ? 'Stock Received' : jobs.some(j => j.status === 'ReadyForStock') ? 'Ready for Stock' : jobs.some(j => ['InProduction', 'MaterialIssued'].includes(j.status)) ? 'In Production' : jobs.some(j => !!j.approval) ? 'Approved' : 'Draft';
      const product = FINISHED_BY_ID.get(item.itemId ?? ''); const balance = product ? physical(ledger, product.id) : null;
      return <Card key={item.id} className="space-y-4"><h2 className="font-semibold text-navy">{item.itemName} · {status}</h2><p className="text-xs text-gray-500">Line reference: {item.id} · Source: {item.fulfillmentSource ?? 'Not selected (legacy order)'}</p><dl className="grid grid-cols-2 gap-3 text-sm lg:grid-cols-6">{[['Ordered', item.quantity], ['Allocated remaining', allocated], ['In production', jobs.filter(j => !['Completed', 'ReadyForStock'].includes(j.status)).reduce((sum, j) => sum + j.qty, 0)], ['Finished goods received', received], ['Dispatched', sent], ['Remaining', item.quantity - sent]].map(([label, value]) => <div key={label}><dt className="text-gray-500">{label}</dt><dd>{value} {item.unit}</dd></div>)}</dl><p className="text-sm">Physical: {balance ?? 'Unknown'} · Reserved: {product ? reserved(ledger, product.id) : 'Unknown'} · Available: {balance === null || !product ? 'Unknown' : balance - reserved(ledger, product.id)} {item.unit}</p>
      {jobs.map(j => <Link key={j.id} to={`/job-cards/${j.id}`} className="mr-3 text-navy underline">{j.jobCardNumber} · {j.status}</Link>)}
      {item.fulfillmentSource === 'manufacturing' && <div className="flex flex-wrap gap-3"><Link to={`/costing?orderId=${order.id}&itemId=${item.id}`} className="rounded-card border px-3 py-2 text-sm text-navy">Open Costing / Estimate</Link>{item.estimateId && <span className="text-sm">{estimates.find(e => e.id === item.estimateId)?.number} · Costing {estimates.find(e => e.id === item.estimateId)?.status}</span>}{item.modelId && !jobs.length && <button disabled={!item.estimateId} className={button} onClick={() => { const model = versions.find(m => m.id === item.modelId && m.revision === item.modelRevision); if (!model) { setError('Model revision not found.'); return; } void createLinked(order.id, item.id, model.id, item.requiredDate ?? '', item.specifications ?? '', [], item.estimateId).then(j => setNotice(`${j.jobCardNumber} created as a linked draft for PM review.`)).catch(e => setError(e instanceof Error ? e.message : 'Unable to create job.')); }}>Create linked draft Job Card</button>}</div>}
      {item.fulfillmentSource === 'manufacturing' && !item.modelId && !jobs.length && <JobDraft onSave={async (model, date, specs, materials) => { try { const j = await createLinked(order.id, item.id, model, date, specs, materials); setNotice(`${j.jobCardNumber} created for PM review.`); setError(''); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to create job.'); } }} />}
      {canFulfill && item.fulfillmentSource && <form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); run(() => allocateStock(order, item, Number(data.get('quantity')), String(data.get('batch')), String(data.get('allocationId')))); }} className="flex flex-wrap items-end gap-3"><input type="hidden" name="allocationId" value={`allocation-${order.id}-${item.id}-${allocations.length}`} /><label>Stock batch<select name="batch" className={ENTRY_INPUT}><option value="reference-stock">Reference stock (batch unavailable)</option>{[...new Set(ledger.movements.filter(m => m.productId === item.itemId && m.batch && m.batch !== 'reference-stock').map(m => m.batch!))].map(batch => <option key={batch}>{batch}</option>)}</select></label><label>Allocate quantity<input name="quantity" required type="number" min="0.000001" step="any" className={ENTRY_INPUT} /></label><button className={button}>Allocate Finished Goods</button></form>}
      {allocations.filter(a => !a.released && a.quantity > a.dispatched).map(a => <form key={a.id} onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const dispatchId = String(f.get('dispatchId')); run(() => dispatch({ id: dispatchId, allocationId: a.id, quantity: Number(f.get('quantity')), date: String(f.get('date')), challan: String(f.get('challan')), destination: String(f.get('destination')), vehicle: String(f.get('vehicle')), remarks: String(f.get('remarks')) })); }} className="space-y-3 rounded-card bg-gray-50 p-4"><input type="hidden" name="dispatchId" value={`dispatch-${a.id}-${ledger.dispatches.length}`} /><h3>Dispatch allocation · {a.batch} · Remaining {a.quantity - a.dispatched} {item.unit}</h3><div className="grid gap-3 sm:grid-cols-3">{[['quantity', 'Dispatch Quantity', 'number'], ['date', 'Dispatch Date', 'date'], ['challan', 'Delivery Note / Challan', 'text'], ['destination', 'Destination', 'text'], ['vehicle', 'Transport / Vehicle', 'text'], ['remarks', 'Remarks', 'text']].map(([name, label, type]) => <label key={name}>{label}<input name={name} type={type} required={['quantity', 'date', 'challan', 'destination'].includes(name)} defaultValue={name === 'date' ? today() : undefined} step="any" min={name === 'quantity' ? '0.000001' : undefined} className={ENTRY_INPUT} /></label>)}</div><button disabled={!canFulfill} className={button}>Confirm Dispatch / Stock OUT</button></form>)}
      </Card>;
    })}
    <Card className="space-y-3"><h2 className="font-semibold">Dispatch & activity history</h2>{ledger.dispatches.filter(d => d.orderId === order.id).map(d => <div key={d.id} className="border-b py-3"><p>{d.number} · {order.items?.find(i => i.id === d.itemId)?.itemName} · Model: {d.modelName ?? 'Not configured'} · {d.date} · {d.quantity} {d.unit} · {d.status} · {d.batch} · Challan {d.challan} · {d.destination}</p>{d.status === 'Confirmed' && canFulfill && !invoices.some(i => i.dispatchIds.includes(d.id)) && <form className="flex gap-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => reverse(d.id, String(f.get('date')), String(f.get('reason')))); }}><input aria-label="Reversal date" name="date" type="date" required defaultValue={today()} className={ENTRY_INPUT} /><input aria-label="Cancellation reason" name="reason" required placeholder="Cancellation reason" className={ENTRY_INPUT} /><button className={button}>Cancel with reversal</button></form>}</div>)}{ledger.movements.filter(m => m.salesOrderId === order.id).map(m => <p key={m.id} className="text-sm">{m.date} · {m.type} {m.quantity} {m.unit} · {m.reference} · {m.batch} · <Link to="/stock" className="underline">Stock transaction {m.id}</Link>{m.jobCardId && <> · <Link to={`/job-cards/${m.jobCardId}`} className="underline">Job Card</Link></>}</p>)}{order.jobCardIds.map(j => <Link key={j} to={`/job-cards/${j}`} className="mr-3 underline">Job Card {j}</Link>)}</Card>
    <Card><h2 className="font-semibold">Sales documents</h2><p>Order total: {order.currency} {order.orderTotal?.toFixed(2)} · Tax: {order.taxRate ?? 'Not configured'}%</p><button className={button} onClick={() => setInvoiceOpen(!invoiceOpen)}>Create Invoice</button>{invoiceOpen && <InvoiceForm order={order} onSaved={() => setInvoiceOpen(false)} />}</Card>{invoices.filter(i => i.orderId === order.id).map(i => <InvoiceView key={i.id} invoice={i} />)}
  </div>;
}
function JobDraft({ onSave }: { onSave: (model: string, date: string, specs: string, materials: import('@/types').JobCardMaterial[]) => Promise<void> }) {
  const { models } = useModels();
  const [materials, setMaterials] = useState<{ id: string; qty: string }[]>([{ id: '', qty: '' }]); const [saving, setSaving] = useState(false);
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); setSaving(true); try { await onSave(String(f.get('model')), String(f.get('date')), String(f.get('specs')), materials.map(row => { const m = RAW_MATERIALS.find(m => m.id === row.id)!; return { id: crypto.randomUUID(), materialId: m?.id, name: m?.name ?? '', unit: m?.unit ?? '', requiredQuantity: Number(row.qty), issuedQuantity: 0 }; })); } finally { setSaving(false); } };
  return <form onSubmit={e => void submit(e)} className="space-y-3 rounded-card border p-4"><h3>Create / Allocate Job Card</h3><p className="text-xs text-amber-700">Editable draft: model BOM quantities are unavailable. Enter reviewed material requirements; no formulas are assumed.</p><label>Model<select required name="model" className={ENTRY_INPUT}><option value="">Select model</option>{models.map(m => <option key={m.id} value={m.id}>{m.name} · {m.billOfMaterials}</option>)}</select></label><label>Required Delivery Date<input required name="date" type="date" className={ENTRY_INPUT} /></label><label>Specifications<textarea name="specs" className={ENTRY_INPUT} /></label>{materials.map((row, i) => <div key={i} className="flex gap-3"><select aria-label={`Required material ${i + 1}`} required value={row.id} onChange={e => setMaterials(materials.map((r, n) => n === i ? { ...r, id: e.target.value } : r))} className={ENTRY_INPUT}><option value="">Select material</option>{RAW_MATERIALS.map(m => <option key={m.id} value={m.id}>{m.name} ({m.unit})</option>)}</select><input aria-label={`Material quantity ${i + 1}`} required type="number" min="0.000001" step="any" value={row.qty} onChange={e => setMaterials(materials.map((r, n) => n === i ? { ...r, qty: e.target.value } : r))} className={ENTRY_INPUT} /></div>)}<button type="button" className={button} onClick={() => setMaterials([...materials, { id: '', qty: '' }])}>Add material</button><button disabled={saving} className={button}>{saving ? 'Creating…' : 'Create linked Job Card'}</button></form>;
}
