import { useState, type FormEvent } from 'react';
import { Card } from '@/components/ui/Card';
import { ENTRY_INPUT } from '@/components/ui/SearchSelect';
import { useInvoices } from '@/context/InvoicesContext';
import { useInventory } from '@/context/InventoryContext';
import { today } from '@/lib/salesOrders';
import { amountInWords, type Invoice } from '@/lib/invoices';
import type { SalesOrder } from '@/types';
const fields = [['number', 'Invoice Number'], ['seller', 'Seller Company Name'], ['sellerAddress', 'Seller Address'], ['sellerTax', 'Seller Tax ID'], ['email', 'Seller Email'], ['contact', 'Seller Contact'], ['billingAddress', 'Buyer Billing Address'], ['deliveryAddress', 'Buyer Delivery Address'], ['buyerTax', 'Buyer Tax ID'], ['paymentTerms', 'Payment Terms'], ['destination', 'Destination'], ['currency', 'Currency']] as const;
export function InvoiceForm({ order, onSaved }: { order: SalesOrder; onSaved: () => void }) {
  const { invoices, create } = useInvoices(); const { ledger } = useInventory(); const [error, setError] = useState(''); const [fiscal, setFiscal] = useState(false);
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const data = Object.fromEntries(fields.map(([key]) => [key, String(f.get(key) ?? '')])) as Record<typeof fields[number][0], string>; try { create(order.id, { ...data, date: String(f.get('date')), dispatchIds: f.getAll('dispatch').map(String), discount: Number(f.get('discount')), taxRate: Number(f.get('taxRate')), fiscalNumber: fiscal ? String(f.get('fiscalNumber')) : undefined, verificationCode: fiscal ? String(f.get('verificationCode')) : undefined }); onSaved(); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to create invoice.'); } };
  const available = ledger.dispatches.filter(d => d.orderId === order.id && d.status === 'Confirmed' && !invoices.some(i => i.dispatchIds.includes(d.id)));
  return <form onSubmit={submit} className="mt-4 space-y-4"><p className="text-xs text-gray-500">Draft sales document. Seller details must come from your company; tax treatment requires confirmation. Invoice creation does not move stock.</p><div className="grid gap-3 sm:grid-cols-3">{fields.map(([key, label]) => <label key={key}>{label}<input required={['number', 'seller', 'billingAddress', 'currency'].includes(key)} name={key} defaultValue={key === 'currency' ? order.currency : undefined} className={ENTRY_INPUT} /></label>)}<label>Invoice Date<input required type="date" name="date" defaultValue={today()} className={ENTRY_INPUT} /></label><label>Discount (before tax)<input required type="number" name="discount" min="0" step="0.01" defaultValue="0" className={ENTRY_INPUT} /></label><label>Applicable transaction VAT / Tax %<input required name="taxRate" type="number" min="0" max="100" step="any" defaultValue={order.taxRate} className={ENTRY_INPUT} /></label></div><fieldset><legend>Confirmed dispatches to invoice</legend>{available.map(d => <label key={d.id} className="mr-4 inline-block"><input name="dispatch" type="checkbox" value={d.id} /> {d.number} · {d.quantity} {d.unit}</label>)}{!available.length && <p>No uninvoiced confirmed dispatches.</p>}</fieldset><label className="block"><input type="checkbox" checked={fiscal} onChange={e => setFiscal(e.target.checked)} /> Configured jurisdiction uses fiscal references</label>{fiscal && <div className="space-y-2"><p className="text-xs text-amber-700">Enter authority-issued references only. This frontend does not certify fiscal documents or generate verification QR codes.</p><label>Fiscal Document Number<input name="fiscalNumber" className={ENTRY_INPUT} /></label><label>Authority Verification Code<input name="verificationCode" className={ENTRY_INPUT} /></label></div>}{error && <p role="alert" className="text-red-700">{error}</p>}<button disabled={!available.length} className="rounded-card bg-navy px-4 py-2 text-white disabled:opacity-50">Create frontend invoice</button></form>;
}
export function InvoiceView({ invoice: i }: { invoice: Invoice }) {
  return <Card className="space-y-4"><div className="flex justify-between"><h2 className="text-xl font-semibold">Invoice {i.number}</h2><span>{i.date}</span></div><p className="text-xs text-amber-700">Frontend sales document · Non-persistent · Fiscal certification unverified</p><div className="grid gap-4 sm:grid-cols-2"><div><h3>Seller: {i.seller}</h3><p>{i.sellerAddress}</p><p>Tax ID: {i.sellerTax || 'Not supplied'}</p><p>{i.email} · {i.contact}</p></div><div><h3>Buyer: {i.buyer}</h3><p>Billing: {i.billingAddress}</p><p>Delivery: {i.deliveryAddress}</p><p>Tax ID: {i.buyerTax || 'Not supplied'}</p></div></div><p>Sales Order: {i.orderNumber} · PO: {i.po} · Delivery notes: {i.challans}</p><p>Dispatch references: {(i.dispatchNumbers ?? i.dispatchIds).join(', ')} · Terms: {i.paymentTerms} · Destination: {i.destination}</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Description', 'Quantity', 'Unit', 'Rate', 'Amount'].map(label => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{i.items.map(item => <tr key={item.itemId}>{[item.description, item.quantity, item.unit, item.rate.toFixed(2), item.amount.toFixed(2)].map((value, n) => <td key={n} className="p-2">{value}</td>)}</tr>)}</tbody></table></div><p>Subtotal: {i.currency} {i.subtotal.toFixed(2)} · Discount: {i.discount.toFixed(2)} · Tax ({i.taxRate}%): {i.tax.toFixed(2)}</p><p className="font-semibold">Grand Total: {i.currency} {i.total.toFixed(2)}</p><p>{amountInWords(i.total, i.currency)}</p>{i.fiscalNumber && <p>Fiscal Document Number: {i.fiscalNumber}</p>}{i.verificationCode && <p>Supplied authority code (unverified): {i.verificationCode}</p>}</Card>;
}
