import { useJobCards } from '@/context/JobCardsContext';
import { emptyMaterial, emptyProcess } from './CostingFields';
import { useState, type FormEvent } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { Card } from '@/components/ui/Card';
import { ENTRY_INPUT } from '@/components/ui/SearchSelect';
import { useCosting } from '@/context/CostingContext';
import { useModels } from '@/context/ModelsContext';
import { useSalesOrders } from '@/context/SalesOrdersContext';
import { useAuth } from '@/context/AuthContext';
import { calculateCost, convertQuantity, newCostingInput, MARKUP_SCENARIOS, customerEstimate, type CostingInput, type CostEstimate } from '@/lib/customCosting';
import { RecipeFields, ProcessFields } from './CostingFields';
const BUTTON = 'rounded-card border border-gray-200 px-3 py-2 text-sm text-navy disabled:opacity-40';
export function CustomCosting() {
  const { cards } = useJobCards();
  const { estimates, save, setStatus, generate, accept } = useCosting(); const { models, versions } = useModels(); const { orders } = useSalesOrders(); const { user } = useAuth(); const [params, setParams] = useSearchParams();
  const [draft, setDraft] = useState<CostingInput | null>(null); const [existingId, setExistingId] = useState<string>(); const [error, setError] = useState(''); const [previewId, setPreviewId] = useState<string>();
  const order = orders.find(o => o.id === params.get('orderId')), item = order?.items?.find(i => i.id === params.get('itemId'));
  const proposedJob = cards.find(c => c.salesOrderId === order?.id && c.salesOrderItemId === item?.id);
  const canCustom = ['admin', 'accounts'].includes(user?.role ?? '');
  const run = (action: () => void) => { try { action(); setError(''); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to update estimate.'); } };
  const begin = (modelId: string) => { const model = versions.find(m => m.id === modelId && (item?.modelRevision ? m.revision === item.modelRevision : m.revision === models.find(latest => latest.id === modelId)?.revision)); if (order && item && model) { setDraft(newCostingInput(order, item, model)); setExistingId(undefined); setError(''); } };
  const submit = (e: FormEvent) => { e.preventDefault(); run(() => { const next = save(draft!, existingId); setDraft(null); setExistingId(next.id); }); };
  let totals: ReturnType<typeof calculateCost> | undefined, validation = '';
  if (draft) { try { totals = calculateCost(draft); } catch(e) { validation = e instanceof Error ? e.message : 'Incomplete costing.'; } }
  const editNumber = (key: keyof CostingInput, n: number) => setDraft(draft ? { ...draft, [key]: n } : null);
  const visible = estimates.filter(e => !order || (e.input.orderId === order.id && (!item || e.input.itemId === item.id)));
  const preview = estimates.find(e => e.id === previewId);
  return <div className="space-y-5"><Card className="space-y-3"><h2 className="font-semibold text-navy">Custom Product Costing & Estimates</h2><p className="text-xs text-gray-500">Session-only. Net purchase prices, explicit units and entered exchange rates. Workbook examples are references, not fixed rates. Markup and gross margin are distinct.</p><div className="grid gap-3 sm:grid-cols-3"><label>Sales Order<select value={order?.id ?? ''} onChange={e => { setParams({ orderId: e.target.value }); setDraft(null); }} className={ENTRY_INPUT}><option value="">Select order</option>{orders.filter(o => o.items?.some(i => i.fulfillmentSource === 'manufacturing')).map(o => <option key={o.id} value={o.id}>{o.orderNumber} · {o.customerName}</option>)}</select></label><label>Custom Order Line<select value={item?.id ?? ''} onChange={e => { setParams({ orderId: order!.id, itemId: e.target.value }); setDraft(null); }} className={ENTRY_INPUT}><option value="">Select line</option>{order?.items?.filter(i => i.fulfillmentSource === 'manufacturing').map(i => <option key={i.id} value={i.id}>{i.itemName} · {i.quantity} {i.unit}</option>)}</select></label><label>Use Model<select value="" disabled={!item} onChange={e => begin(e.target.value)} className={ENTRY_INPUT}><option value="">Open new costing from model</option>{(item?.modelId ? versions.filter(m => m.id === item.modelId && m.revision === item.modelRevision) : models).map(m => <option key={m.id} value={m.id}>{m.name} · Revision {m.revision}</option>)}</select></label></div>{order && <Link to={`/sales-orders/${order.id}`} className="text-sm underline">Return to {order.orderNumber}</Link>}</Card>
  {error && <p role="alert" className="rounded-card bg-red-50 p-3 text-red-700">{error}</p>}
  {draft && <form onSubmit={submit} className="space-y-5"><Card className="space-y-3"><h3 className="font-semibold">A. Product Details</h3><p>{draft.customer} · {draft.product} · {draft.quantity} {draft.unit} · Model Revision {draft.modelRevision}</p><label>Specifications<textarea value={draft.specifications} onChange={e => setDraft({ ...draft, specifications: e.target.value })} className={ENTRY_INPUT} /></label><p className="text-xs text-amber-700">This sheet costs the entire stated order. Enter total material/process quantities for that order. Order units are never treated as material mass automatically.</p></Card>
  <Card className="space-y-3"><h3 className="font-semibold">B. Material Recipe</h3>{proposedJob?.requirementsReviewRequired && <div className="space-y-3 rounded-card bg-amber-50 p-3"><p className="text-sm">Job Card routing/materials changed. Review revised quantities and process rates before approval.</p><button type="button" className={BUTTON} onClick={() => setDraft({ ...draft, recipeMode: 'quantities', materials: (proposedJob.requiredMaterials ?? []).map(m => ({ ...(draft.materials.find(row => row.materialId === m.materialId) ?? emptyMaterial()), materialId: m.materialId ?? '', name: m.name, quantity: m.requiredQuantity, unit: m.unit, priceUnit: draft.materials.find(row => row.materialId === m.materialId)?.priceUnit ?? m.unit })), processes: (proposedJob.productionStages ?? []).filter(s => s.required && s.kind === 'production').map(s => ({ ...(draft.processes.find(p => p.stageId === s.id) ?? emptyProcess()), stageId: s.id, name: s.name })) })}>Apply proposed materials and route stages to this draft</button><p className="text-xs">Prices match by stable material ID and process-stage ID. New process rates remain blank for review; no cost formula is invented.</p></div>}<div className="flex flex-wrap gap-3"><label>Recipe basis<select value={draft.recipeMode} onChange={e => setDraft({ ...draft, recipeMode: e.target.value as CostingInput['recipeMode'] })} className={ENTRY_INPUT}><option value="quantities">Actual total quantities</option><option value="percentages">Proportions × production batch</option></select></label><label>Total batch quantity<input type="number" min="0" step="any" value={draft.batchQuantity} onChange={e => editNumber('batchQuantity', e.target.valueAsNumber)} className={ENTRY_INPUT} /></label><label>Batch unit<input value={draft.batchUnit} onChange={e => setDraft({ ...draft, batchUnit: e.target.value })} className={ENTRY_INPUT} /></label></div>{draft.recipeMode === 'quantities' && totals && totals.materials.every(m => m.mixingPercent !== null) && <button type="button" className={BUTTON} onClick={() => setDraft({ ...draft, recipeMode: 'percentages', batchUnit: 'kg', batchQuantity: totals!.materials.reduce((sum, m) => sum + convertQuantity(m.quantity, m.unit, 'kg'), 0), materials: draft.materials.map((m, i) => ({ ...m, percentage: totals!.materials[i].mixingPercent! })) })}>Convert actual mix to percentage recipe</button>}<RecipeFields materials={draft.materials} mode={draft.recipeMode} totals={totals} onChange={materials => setDraft({ ...draft, materials })} /><p className="text-xs text-gray-500">Supported mass conversions: 1 kg = 1,000 g; 1 tonne = 1,000 kg. Other units must match exactly. Mixing percentages are shown only for comparable mass units.</p></Card>
  <Card className="space-y-3"><h3 className="font-semibold">C. Currency & Exchange Rate</h3><label>Estimate Currency<select value={draft.currency} onChange={e => setDraft({ ...draft, currency: e.target.value as CostingInput['currency'] })} className={ENTRY_INPUT}><option>UGX</option><option>USD</option></select></label><p className="text-xs text-gray-500">Each recipe exchange rate is estimate currency per one purchase currency (e.g. UGX per USD). Same-currency conversion uses 1. Enter new rates when changing currencies; no current rate overrides a saved revision. Purchase prices are entered net; VAT removal from the source workbook needs client clarification.</p></Card>
  <Card className="space-y-3"><h3 className="font-semibold">D. Production Costs</h3><ProcessFields stages={proposedJob?.productionStages ?? versions.find(m => m.id === draft.modelId && m.revision === draft.modelRevision)?.routing} processes={draft.processes} onChange={processes => setDraft({ ...draft, processes })} /><div className="grid gap-3 sm:grid-cols-2">{(['overheads', 'additionalCosts'] as const).map(key => <label key={key}>{key === 'overheads' ? 'Other Overheads' : 'Additional Applicable Costs'} ({draft.currency})<input type="number" min="0" step="any" value={draft[key]} onChange={e => editNumber(key, e.target.valueAsNumber)} className={ENTRY_INPUT} /></label>)}</div><p className="text-xs text-gray-500">Printing ink is a separately labelled recipe cost group. Process rates are in estimate currency; fixed charges apply once and other bases use the entered quantity.</p></Card>
  <Card className="space-y-3"><h3 className="font-semibold">E. Waste Allowance</h3><label>Waste %<input type="number" min="0" max="100" step="any" value={draft.wastePercent} onChange={e => editNumber('wastePercent', e.target.valueAsNumber)} className={ENTRY_INPUT} /></label><label>Cost allowance basis<select value={draft.wasteBasis} onChange={e => setDraft({ ...draft, wasteBasis: e.target.value as CostingInput['wasteBasis'] })} className={ENTRY_INPUT}><option value="materials">Materials + ink</option><option value="materials-and-processes">Materials + ink + processes</option></select></label><p className="text-xs text-gray-500">Waste is an explicit cost allowance. It does not silently increase material requirements or imply production yield.</p></Card>
  <Card className="space-y-3"><h3 className="font-semibold">F. Profit / Markup</h3><label>Pricing Method<select disabled={!canCustom} value={draft.pricingMethod} onChange={e => setDraft({ ...draft, pricingMethod: e.target.value as CostingInput['pricingMethod'] })} className={ENTRY_INPUT}><option value="markup">Markup on Cost (workbook method)</option><option value="gross-margin">Gross Profit Margin (Accounts/Admin)</option></select></label><label>{draft.pricingMethod === 'markup' ? 'Markup on Cost %' : 'Gross Profit Margin %'}{canCustom ? <input type="number" min="0" step="any" value={draft.markupPercent} onChange={e => editNumber('markupPercent', e.target.valueAsNumber)} className={ENTRY_INPUT} /> : <select value={draft.markupPercent} onChange={e => editNumber('markupPercent', Number(e.target.value))} className={ENTRY_INPUT}>{MARKUP_SCENARIOS.map(n => <option key={n}>{n}</option>)}</select>}</label>{totals && <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{['Markup on Cost', 'Production Cost', 'Profit', 'Before Tax', 'Charges', 'Tax', 'Final Price', 'Unit Price', 'Order Estimate'].map(label => <th key={label} className="p-2 text-gray-500">{label}</th>)}</tr></thead><tbody>{MARKUP_SCENARIOS.map(n => { const t = calculateCost({ ...draft, pricingMethod: 'markup', markupPercent: n }); return <tr key={n}>{[`${n}%`, t.costOfProduction, t.profit, t.sellingBeforeTax, t.charges, t.tax, t.grandTotal, t.unitSellingPrice, t.grandTotal].map((v, j) => <td key={j} className="p-2">{typeof v === 'number' ? v.toFixed(2) : v}</td>)}</tr>; })}</tbody></table></div>}</Card>
  <Card className="space-y-3"><h3 className="font-semibold">G. Taxes & Charges</h3><div className="grid gap-3 sm:grid-cols-3">{(['taxPercent', 'chargePercent', 'minimumCharge'] as const).map(key => <label key={key}>{{ taxPercent: 'Applicable Tax %', chargePercent: 'Additional Charge %', minimumCharge: `Minimum Charge (${draft.currency}, converted by user)` }[key]}<input type="number" min="0" step="any" value={draft[key]} onChange={e => editNumber(key, e.target.valueAsNumber)} className={ENTRY_INPUT} /></label>)}</div><label><input type="checkbox" checked={draft.taxOnCharges} onChange={e => setDraft({ ...draft, taxOnCharges: e.target.checked })} /> Include charges in tax base</label><p className="text-xs text-gray-500">Charge = higher of configured minimum or percentage of selling price. No levy rate, USD minimum or 18% VAT is imposed universally.</p></Card>
  <Card className="space-y-3"><h3 className="font-semibold">H. Final Estimate</h3>{totals && <CostBreakdown estimate={{ totals, input: draft }} />}<div className="grid gap-3 sm:grid-cols-3"><label>Valid Until<input type="date" required value={draft.validityDate} onChange={e => setDraft({ ...draft, validityDate: e.target.value })} className={ENTRY_INPUT} /></label><label>Delivery Terms<input value={draft.deliveryTerms} onChange={e => setDraft({ ...draft, deliveryTerms: e.target.value })} className={ENTRY_INPUT} /></label><label>Customer Remarks<input value={draft.remarks} onChange={e => setDraft({ ...draft, remarks: e.target.value })} className={ENTRY_INPUT} /></label></div>{validation && <p role="status" className="text-amber-700">{validation}</p>}<button disabled={!totals} className={BUTTON}>Save costing {existingId ? 'revision' : 'draft'}</button><button type="button" className={`${BUTTON} ml-3`} onClick={() => setDraft(null)}>Cancel</button></Card></form>}
  {visible.map(e => <Card key={e.id} className="space-y-3"><h3 className="font-semibold">{e.number} · Revision {e.revision} · {e.input.product}</h3><p className="text-sm">Costing: {e.status} · Customer: {e.customerAcceptance} · {e.input.currency} {e.totals.grandTotal.toFixed(2)}</p>{e.reviewReason && <p className="text-amber-700">Review required: {e.reviewReason}</p>}<div className="flex flex-wrap gap-2"><button className={BUTTON} onClick={() => { setDraft(structuredClone(e.input)); setExistingId(e.id); }}>{e.approvedAt || e.generatedAt || e.usedByJobCardId ? 'Create New Revision' : 'Edit Draft'}</button>{e.status === 'Draft' && <button className={BUTTON} onClick={() => run(() => setStatus(e.id, 'Pending Review'))}>Send for Review</button>}{e.status === 'Pending Review' && canCustom && <><button className={BUTTON} onClick={() => run(() => setStatus(e.id, 'Approved'))}>Approve Costing</button><button className={BUTTON} onClick={() => run(() => setStatus(e.id, 'Revision Required'))}>Request Revision</button></>}<button className={BUTTON} disabled={e.status === 'Superseded' || e.status === 'Revision Required'} onClick={() => run(() => { generate(e.id); setPreviewId(e.id); })}>Generate Estimate</button>{e.generatedAt && <button className={BUTTON} onClick={() => setPreviewId(e.id)}>Preview Estimate</button>}{e.status === 'Approved' && e.generatedAt && <><button className={BUTTON} onClick={() => run(() => accept(e.id, true))}>Record Customer Acceptance</button><button className={BUTTON} onClick={() => run(() => accept(e.id, false))}>Record Customer Rejection</button></>}</div></Card>)}{!visible.length && <p className="text-sm text-gray-500">Select a custom order line and model to create its costing estimate.</p>}
  {preview && <CustomerEstimatePreview estimate={preview} modelName={versions.find(m => m.id === preview.input.modelId && m.revision === preview.input.modelRevision)?.name ?? preview.input.modelId} onClose={() => setPreviewId(undefined)} />}
  </div>;
}
export function CostBreakdown({ estimate }: { estimate: Pick<CostEstimate, 'input' | 'totals'> }) { const t = estimate.totals; return <dl className="grid gap-3 text-sm sm:grid-cols-3">{[['Materials', t.materialCost], ['Printing Ink', t.inkCost], ['Process Costs', t.processCost], ['Waste Allowance', t.wasteCost], ['Overheads', estimate.input.overheads], ['Additional Costs', estimate.input.additionalCosts], ['Cost of Production', t.costOfProduction], ['Profit / Markup', t.profit], ['Before Tax', t.sellingBeforeTax], ['Charges', t.charges], ['Applicable Tax', t.tax], ['Grand Total', t.grandTotal], ['Unit Selling Price (tax inclusive)', t.unitSellingPrice]].map(([label, value]) => <div key={label}><dt className="text-gray-500">{label}</dt><dd>{estimate.input.currency} {Number(value).toFixed(2)}</dd></div>)}</dl>; }
export function CustomerEstimatePreview({ estimate, modelName, onClose }: { estimate: CostEstimate; modelName: string; onClose: () => void }) {
  const e = customerEstimate(estimate);
  return <div role="dialog" aria-modal="true" aria-label="Customer estimate preview" className="estimate-overlay fixed inset-0 z-[60] overflow-y-auto bg-navy/30 p-4"><section className="customer-estimate mx-auto max-w-3xl space-y-5 rounded-card bg-white p-8 shadow-xl"><div className="flex justify-between"><h2 className="text-xl font-semibold text-navy">Estimate {e.number} · Revision {e.revision}</h2><span>{e.date}</span></div><p className="text-sm">{estimate.status === 'Approved' ? 'Internally approved estimate' : `${estimate.status} estimate — subject to review`} · Customer acceptance: {estimate.customerAcceptance}</p><dl className="grid gap-3 sm:grid-cols-2">{[['Customer', e.customer], ['Product', e.product], ['Model', `${modelName} · Revision ${e.modelRevision}`], ['Specifications', e.specifications], ['Quantity', `${e.quantity} ${e.unit}`], ['Unit Selling Price (tax inclusive)', `${e.currency} ${e.unitSellingPrice.toFixed(2)}`], ['Subtotal before charges/tax', `${e.currency} ${e.subtotal.toFixed(2)}`], ['Applicable Charges', `${e.currency} ${e.charges.toFixed(2)}`], ['Applicable Tax', `${e.currency} ${e.tax.toFixed(2)}`], ['Grand Total', `${e.currency} ${e.grandTotal.toFixed(2)}`], ['Valid Until', e.validityDate], ['Delivery Terms', e.deliveryTerms], ['Remarks', e.remarks]].map(([label, value]) => <div key={label}><dt className="text-sm text-gray-500">{label}</dt><dd>{value || 'Not supplied'}</dd></div>)}</dl><p className="text-xs text-gray-500">Frontend estimate preview. Not a fiscal invoice.</p><div className="flex gap-3 print:hidden"><button type="button" className={BUTTON} onClick={() => window.print()}>Print Customer Estimate</button><button type="button" className={BUTTON} onClick={onClose}>Close</button></div></section></div>;
}
