"""Read the supplied workbook; regenerate the frontend reference without editing Excel.
Usage: python scripts/extract-raw-materials.py <workbook.xlsx>
"""
import datetime
import json
import pathlib
import sys
import openpyxl

path = pathlib.Path(sys.argv[1])
formulas = openpyxl.load_workbook(path, data_only=False)
values = openpyxl.load_workbook(path, data_only=True)
materials, movements = [], []
families = {'HDPE', 'PP', 'LDPE', 'LLDPE', 'MASTER BATCH', 'ADDITIVES',
            'INKS & SOLVENTS', 'RECYCLE MATERIAL', 'CRUSHED MATERIAL'}
for sheet in formulas:
    cached = values[sheet.title]
    family = None
    for row in range(3, sheet.max_row + 1):
        name = sheet.cell(row, 1).value
        if not isinstance(name, str) or not name.strip():
            continue
        name = ' '.join(name.split())
        if name in families:
            family = name
            continue
        if family is None:
            continue
        category = 'ink' if family == 'INKS & SOLVENTS' else 'recycled' if family in {'RECYCLE MATERIAL', 'CRUSHED MATERIAL'} else 'virgin'
        ident = f'excel-{row}'
        opening = cached.cell(row, 4).value
        # Ink rows contain no recorded balance. Do not present blanks as zero stock.
        known = opening is not None or any(isinstance(sheet.cell(row, c).value, (int, float)) for c in range(5, 67))
        material = dict(id=ident, name=name, family=family, category=category, unit='kg',
                        openingStock=round(opening or 0, 6) if known else None,
                        openingDate='2026-09-01', sourceRow=row,
                        sourceClosingStock=cached.cell(row, 69).value if known else None)
        materials.append(material)
        for col in range(5, 67):
            quantity = sheet.cell(row, col).value
            if not isinstance(quantity, (int, float)) or quantity == 0:
                continue
            date = cached.cell(1, col if col % 2 else col - 1).value
            assert isinstance(date, datetime.datetime)
            movements.append(dict(id=f'excel-{row}-{col}', date=date.strftime('%Y-%m-%d'),
                                  materialId=ident, materialName=name, category=category,
                                  movementType='IN' if col % 2 else 'OUT', quantity=quantity,
                                  unit='kg', reference=f'{sheet.title}!{sheet.cell(row, col).coordinate}',
                                  remarks='September 2026 physical stock workbook'))
        if known:
            closing = round((opening or 0) + sum(m['quantity'] * (1 if m['movementType'] == 'IN' else -1) for m in movements if m['materialId'] == ident), 6)
            assert abs(closing - material['sourceClosingStock']) < 0.00001, (name, closing)
target = pathlib.Path(__file__).resolve().parents[1] / 'src/lib/rawMaterialReference.ts'
target.write_text('// Generated by scripts/extract-raw-materials.py. Source: ' + path.name + '\n'
                  + "import type { RawMaterial, RawMaterialMovement } from './rawMaterialData';\n"
                  + 'export const REFERENCE_MATERIALS: RawMaterial[] = ' + json.dumps(materials, indent=2) + ';\n'
                  + 'export const REFERENCE_MOVEMENTS: RawMaterialMovement[] = ' + json.dumps(movements, indent=2) + ';\n', encoding='utf-8')
print(json.dumps(dict(materials=len(materials), categories={c: sum(m['category'] == c for m in materials) for c in ['virgin', 'recycled', 'ink']}, families=sorted({m['family'] for m in materials}), movements=len(movements))))
